### ISSUE TITLE
Error validacion rut digito verificador K

### ISSUE THREAD

**Issue by mickyys** [cgustav/dart_rut_validator#2]
Hola, al validar un rut con dígito verificador K tengo error de validación (rut correcto) ya que retorna 0 para su comparación en la function **isValid**.

Por lo que se debe modificar el retorno de "0" por "K" en la function **_calcMod11** de la clase **_RUTValidatorUtils**

Saludos.

![image](https://user-images.githubusercontent.com/1743768/78319845-7172ea00-753e-11ea-813b-7e2fa9c1ec95.png)

![image](https://user-images.githubusercontent.com/1743768/78319866-7b94e880-753e-11ea-8372-5b18e5202a79.png)

**Comment by cgustav** [comment]
Gracias por la observación, el problema ya fue corregido en el commit [1933b55](https://github.com/cgustav/dart_rut_validator/commit/1933b55dd047821b467afa0f5ab49009570d49d9)
