### ISSUE TITLE
Por favor, agregar soporte para null safety para flutter 2.x ya que ahora es incompatible

### ISSUE THREAD

**Issue by rzablah** [cgustav/dart_rut_validator#4]

**Comment by agueroveraalvaro** [comment]
Hola, favor de agregar compatibilidad con null-safety

**Comment by Grandpasoul** [comment]
Me sumo a esta petición, el plugin funciona impecable, pero necesita null safety

**Comment by ramonchop** [comment]
Hice un fork para actualizar la versión mientras el autor lo corrige.


  dart_rut_validator:
    git: https://github.com/ramonchop/dart_rut_validator.git

**Comment by agueroveraalvaro** [comment]
> Hice un fork para actualizar la versión mientras el autor lo corrige.
> 
> dart_rut_validator: git: https://github.com/ramonchop/dart_rut_validator.git

Muchas gracias!

**Comment by cgustav** [comment]
Gracias al aporte de @ramonchop la librería ya cuenta con soporte para Null safety!
Mil disculpas por la demora, procedo a cerrar el hilo.
